### ISSUE TITLE
Highstock (Highcharts) not working in Chartkick 3.0.1

### ISSUE THREAD

**Issue by lettergram** [ankane/chartkick#450]
In Chartkick 2.3.3 there was no issues using highstock v5. 

However, with the transition to 3.0.1 I have been unable to use it, regular highcharts works fine. 

There are two errors.

First error:

    Error: No charting library found for LineChart

https://github.com/ankane/chartkick/blob/c9ad62d9ae48fec50ffa876f5c271a0c537d0754/vendor/assets/javascripts/chartkick.js#L1750

Second error:

    TypeError: this.library.charts.load is not a function

On https://github.com/ankane/chartkick/blob/c9ad62d9ae48fec50ffa876f5c271a0c537d0754/vendor/assets/javascripts/chartkick.js#L1425

I've played around with it, and I'm not fully understanding why this wont work.

**Comment by lettergram** [comment]
@ankane I know it doesn't officially, it just has all the same base functions as highcharts - which is why I was just curious it would work with 2.3.3 and not 3.0.1. If you don't have time, that's fine; thanks anyway :man_shrugging:

**Comment by ankane** [comment]
Please keep it constructive.
