### ISSUE TITLE
$().size is not a function after upgrading jquery to 3.x

### ISSUE THREAD

**Issue by barmic12** [ankane/chartkick#554]
**Describe the bug**
After upgrading jquery to 3.x, an error related to .size function appeared:

```
Uncaught TypeError: b.size is not a function
    at ha (Chart.bundle.source.js:8925)
    at a (Chart.bundle.source.js:8922)
    at HTMLDocument.ba (Chart.bundle.source.js:8922)
    at mightThrow (Chart.bundle.source.js:1298)
    at process (Chart.bundle.source.js:1366)
```

I use chartkick with Sprockets:
```
//= require chartkick
//= require Chart.bundle
```

Probably it's related to:
>$().size is deprecated in 1.8 and removed in 3.0.

Reference: https://api.jquery.com/size/ 1.2k

**To reproduce**
Use:
- chartkick 3.4.2
- jQuery 3.x

In application.js:
```
//= require chartkick
//= require Chart.bundle
```

**Comment by ankane** [comment]
Hey @barmic12, I'm not sure how to reproduce. It looks like the error is coming from Chart.js, but as far as I know, Chart.js doesn't depend on jQuery.

**Comment by ankane** [comment]
Cleaning up issues (no response and doesn't appear to be caused by Chartkick)
